### ISSUE TITLE
Travisify scijava-maven-plugin

### ISSUE THREAD

**Issue by stelfrich** [scijava/scijava-maven-plugin#14]
The project is not even build with Jenkins anymore, we should migrate to Travis.

**Comment by ctrueden** [comment]
Aah, I have had a commit sitting for over 9 months that does the conversion. But it doesn't work yet, so I didn't push it. I'll take a quick look again, but there is some difficulty with upgrading the parent pom-scijava version to a new-enough one. 😦

**Comment by ctrueden** [comment]
I pushed some experiments and thoughts to the [travis-ci branch](https://github.com/scijava/scijava-maven-plugin/compare/travis-ci). I do not have any more time to get this working right now, but please feel free to investigate in the meantime. Otherwise, I'm sure I'll return to it eventually—we do need to move this component forward to remain compatible with the current BOM.

**Comment by stelfrich** [comment]
> I do not have any more time to get this working right now, but please feel free to investigate in the meantime.

I stumbled over a similar issue when working on #15 but got it sorted out. We could merge #15 first, travisify the repository, and then get the POM cleaned up (if required). Otherwise, we might run into trouble merging the PR.

If you'd like to travisify first, I can cherry-pick the interesting parts from the PR to a dedicated PR. I'll do the work either way, @ctrueden!

**Comment by ctrueden** [comment]
Addressed by 8b9d67f83d593b61aa70989f8a80e10df3f4bda6.
